name: Zlato-Robot

on:
  schedule:
    # Čas v UTC (14:35 UTC = 16:35 v Praze)
    # Spouští se v 09:05, 15:35 a 20:05 (jen pondělí až pátek)
    - cron: '05 07 * * 1-5'
    - cron: '35 13 * * 1-5'
    - cron: '05 18 * * 1-5'
  workflow_dispatch: # Umožní ti to spustit i ručně tlačítkem

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      - run: pip install -r requirements.txt
      - env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
        run: python robot.py
